require File.dirname(__FILE__) + '/base' unless defined?(Capper)

require "capper/rails"

Capper.load do
  namespace :sass do
    desc "Updates the stylesheets generated by Sass"
    task :update, :roles => :app do
      run "cd #{release_path} && RAILS_ENV=#{rails_env} bundle exec rake sass:update"
    end
  end

  before "deploy:restart", "sass:update"
end
